### ISSUE TITLE
[Request] SuperTuxKart icon

### ISSUE THREAD

**Issue by Vistaus** [Magog64/SURU-PLUS#5]
It would be great if you could add an icon for SuperTuxKart :)
http://supertuxkart.net/

**Comment by Magog64** [comment]
done and loaded, check that it works

**Comment by Vistaus** [comment]
Works fine and looking gooood! Thank you so much for creating it (and also in such short time!) :smile:

**Comment by gusbemacbe** [comment]
@Vistaus, you could have provided detailed informations required for not making Andrea having difficulty. Please provide next time.

**Comment by Vistaus** [comment]
@gusbemacbe What was difficult about it if he managed to create an icon within two hours of me requesting it? (not to mention the fact that SuperTuxKart is one of the most well-known Linux games)

**Comment by gusbemacbe** [comment]
For example, in some distributions, your favourite app can have the same icon name, but in others distributions, it has another different icon name, or if your app is a snap, a native Debian or source code. Because not all icons work with the same app. Therefore, we need to know the distribution and version, app type (for example, snap, native or source code), app name, icon name and its path located in a desktop file. 

It happened with many snap apps and few source code, AppImage and native Debian apps, including GitHub Desktop, whose icons are not well displayed. See the reference: https://github.com/Magog64/SURU-PLUS#many-apps-are-not-well-displayed. 

Imagine in different distributions and in different app types:
```
Icon=appimage-supertax
Icon=supertax
Icon=supertaxt_supertax
```
